FROM mcr.microsoft.com/dotnet/sdk:10.0 AS builder

WORKDIR /src

COPY Driventa.slnx .
COPY Driventa.API/ Driventa.API/
COPY src/ src/

RUN dotnet restore Driventa.slnx

RUN dotnet publish Driventa.API/Driventa.API.csproj \
    -c Release \
    -o /app/publish \
    --no-restore


FROM mcr.microsoft.com/dotnet/aspnet:10.0

WORKDIR /app

COPY --from=builder /app/publish .

ENV ASPNETCORE_URLS=http://+:$PORT

EXPOSE 80

ENTRYPOINT ["dotnet", "Driventa.API.dll"]